Add affirmative step.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,9 +17,11 @@ jobs:
         set -x
         # DEBUG END
         git_config="$(git config -l)"
-        # [[ "$git_config" =~ "user.name" ]] && \
-        #   echo >&2 "Unexpected git config user.name."$'\n'"$git_config" && exit 1
-        [[ "$git_config" =~ "user.name" ]] && echo "FOUND IT"
+        [[ "$git_config" =~ "user.name" ]] && \
+          echo >&2 "Unexpected git config user.name."$'\n'"$git_config" && exit 1
+        echo "user.name not found"
+        # [[ "$git_config" =~ "user.name" ]] && echo "FOUND IT"
+        # [[ "$git_config" =~ "advice" ]] && echo "FOUND IT"
     - uses: ./
     - name: Confirm git config is set
       shell: bash
